config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "artists/subscribe" , to: "artists#subscribe" # needs consistency
  get "artists/explore" , to: "artists#explore", as: "artist_explore" # needs consistency
  get "artists/:id/profile", to: "artists#profile" , as: "artist_profile"
  get "artists/:id/support", to: "artists#support" , as: "artist_support"
  get "artists/:id/projects", to: "artists#projects" , as: "artist_fan_projects"

  resources :artists do 
    resources :artist_profiles
    resources :posts
    resources :projects
  end

  get "fans/:fan_id/subscriptions" , to: "fans#subscriptions", as: "fan_subscriptions"
  get "fans/:fan_id/my_collection" , to: "fans#my_collection", as: "fan_my_collection"
  resources :fans do 
    resources :fan_accounts
    resources :fan_profiles
    resources :artists
  end


  root "artists#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_one  :artist_profile
  has_many :posts
  has_many :projects
  has_many :artist_fans
  has_many :fans , through: :artist_fans
end

app/models/artist_fan.rb
class ArtistFan < ApplicationRecord
  belongs_to :fan
  belongs_to :artist
end

app/models/artist_profile.rb
class ArtistProfile < ApplicationRecord
  belongs_to :artist
end

app/models/fan.rb
class Fan < ApplicationRecord
  has_one  :fan_account
  has_one  :fan_profile
  has_many :fan_projects
  has_many :artist_fans 
  has_many :artists , through: :artist_fans
end

app/models/fan_account.rb
class FanAccount < ApplicationRecord
  belongs_to :fan
end

app/models/fan_profile.rb
class FanProfile < ApplicationRecord
  belongs_to :fan
end

app/models/fan_project.rb
class FanProject < ApplicationRecord
  belongs_to :fan
  belongs_to :project
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :artist
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:show, :profile,:support, :projects]
  before_action :is_there_a_fan?
  
  def index
    @artists = Artist.all
  end

  def show

  end

  def subscribe 
    @artist = Artist.find(params[:artist_id])
    @artist.artist_fans.create(fan_id: params[:fan_id],
                               artist_name: @artist.artist_profile.name,
                               artist_image_uri: @artist.artist_profile.image_url,
                               number_of_projects: 0,
                               number_of_messages: 0,
                               number_of_posts: 0
                              
                              )
    redirect_to fan_subscriptions_path(@fan)
    
  end

  def profile

    @profile = @artist.artist_profile


    respond_to do |format|
      format.html
      format.json { render json: @profile }
    end

  end

  def posts

  end

  def projects 
    @projects = @artist.projects
    respond_to do |format|
      format.html
      format.json { render json: @projects }
    end

  end

  # called when an fan supports an artist
  def support
    # get the project
    # get the fan
    # check whether the fan has more or equal money than support
    # if so support it else throw error
    @project = Project.find(params[:project_id])

    if @fan.fan_account.balance >= @project.support
      @fan.fan_projects.create(project_id: @project.id)
      number_of_current_supports = @project.supports
      @project.update(supports: number_of_current_supports + 1)
      # add one to the number of supports
      redirect_to fan_subscriptions_path(@fan)
    else 
      redirect_to artist_fan_projects_path(@artist)
    end
    

  end


  def explore 
    # check for any filters or tags
    @artists = Artist.all
    @creator_short_profiles = []

    @artists.each do |artist|
      artist_profile = artist.artist_profile 
      @creator_short_profiles << CreatorShortProfile.new(
        artist.id,
        artist_profile.image_url,
        artist_profile.name,
        0,0)
    end
    respond_to do |format|
      format.html
      format.json { render json: @creator_short_profiles }
    end

  end

  private 
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def is_there_a_fan?
    if params[:fan_id]
      @fan = Fan.find(params[:fan_id])
    else 
      @fan = nil 
    end
  end
end

class CreatorShortProfile 
  attr_accessor :creator_id
  attr_accessor :image_url
  attr_accessor :name
  attr_accessor :number_of_followers
  attr_accessor :number_of_plays

  def initialize(creator_id, image_url, name, followers, plays )
    @creator_id = creator_id
    @image_url = image_url 
    @name = name 
    @number_of_followers = followers 
    @number_of_plays = plays
    
  end
end

class CreatorProfile 
  attr_accessor :id
  attr_accessor :creator_id
  attr_accessor :image_url
  attr_accessor :name
  attr_accessor :bio
  attr_accessor :city
  attr_accessor :number_of_followers
  attr_accessor :number_of_plays
  attr_accessor :tag
end

app/controllers/fan_accounts_controller.rb
class FanAccountsController < ApplicationController

  before_action :set_fan

  def show

  end

  private 
  def set_fan
    @fan = Fan.find(params[:fan_id])
  end
end

app/controllers/fans_controller.rb
class FansController < ApplicationController

  before_action :set_fan

  def subscriptions

    @subscribed_artist_id_from_union_table = ArtistFan.where(fan_id: params[:fan_id])
    #@subscribed_artists = Artist.find(@subscribed_artist_id_from_union_table)
    @subscribed_artists = []
    @subscribed_artist_id_from_union_table.each do |artist_fan_union|
      @subscribed_artists << Artist.find(artist_fan_union.artist_id)
    end

    respond_to do |format|
      format.html
      format.json { render json: @subscribed_artist_id_from_union_table }
    end

  end

  def my_collection
    @my_collection = []
    fan_projects = @fan.fan_projects
    fan_projects.each do |fan_project|
      @my_collection << Project.find(fan_project.project_id)
    end
    
  end


  private 
  def set_fan
    if params[:fan_id]
      @fan = Fan.find(params[:fan_id])
    else 
      @fan = []
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_artist 

  def index
    @posts =  @artist.posts.all
  end

  private 
  def set_artist 
    @artist = Artist.find(params[:artist_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  

  before_action :set_artist

  def index
    @projects = @artist.projects
  end

  private 
  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_profiles_helper.rb
module ArtistProfilesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/fan_accounts_helper.rb
module FanAccountsHelper
end

app/helpers/fans_helper.rb
module FansHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/artists/explore.html.erb
<%if @fan %>
  <p> there is a fan </p>
<ul>
  <% @artists.each do |artist| %>
    <%= link_to "#{artist.name}" , artist_profile_path(id: artist.id,fan_id: @fan.id) %> <br>
  <% end %>
</ul>

<%else%>

<ul>
  <% @artists.each do |artist| %>
    <%= link_to "#{artist.name}" , artist %> <br>
  <% end %>
</ul>
<%end%>

app/views/artists/index.html.erb
<%if @fan %>
  <p> there is a fan </p>
<ul>
  <% @artists.each do |artist| %>
    <%= link_to "#{artist.name}" , artist_profile_path(id: artist.id,fan_id: @fan.id) %> <br>
  <% end %>
</ul>

<%else%>

<ul>
  <% @artists.each do |artist| %>
    <%= link_to "#{artist.name}" , artist %> <br>
  <% end %>
</ul>
<%end%>

app/views/artists/profile.html.erb
<img src=<%= @profile.image_url%>
<p> <%= @profile.name %> </p>
<p> <%= @profile.bio %> </p>
<p> <%= @profile.city %> </p>
<%= link_to "Subscribe", artists_subscribe_path(artist_id: @artist.id , fan_id: @fan.id) %>

<h1>Posts </h1>

<% @artist.posts.each do |post| %>
  <h2> <%= post.caption %> </h2>
  <img src=<%= post.image_url %> >
  <p>Likes: <%= post.like %> </p>
<%end%>

app/views/artists/projects.html.erb
<% @projects.each do |project| %>
  <p> <%= project.title %> </p>
  <p> Support: <%= project.support%>Ksh </p>
  <%= link_to "Support" , artist_support_path(@artist , fan_id: @fan.id, project_id: project.id)%>
<% end %>

app/views/artists/show.html.erb
<% if @fan %>
  <p> There is a fan </P
<p> <%= @artist.name%> </p>
<%= link_to "Subscribe" , artists_subscribe_path(artist_id: @artist.id , fan_id: @fan.id) %> 
<%else%>
<p> <%= @artist.name%> </p>
<%= link_to "Subscribe" %> 
<%end%>

app/views/fan_accounts/show.html.erb
<p> Name: <%= @fan.name %> </p>
<p> Balance: <%= @fan.fan_account.balance %> </p>

app/views/fans/my_collection.html.erb
<% @my_collection.each do |project| %>
  <p> <%= project.title %> </p>
  <p> Support: <%= project.support%>Ksh </p>
  <p> Supports: <%= project.supports%> </p>
<% end %>

app/views/fans/subscriptions.html.erb
<% if @subscribed_artists %>
  <ul>
    <% @subscribed_artists.each do |artist| %>
      <%= link_to artist.name , artist_fan_projects_path(id: artist , fan_id: @fan.id)%>
      <li> <%= artist.name %> </li>
    <%end%>
  </ul>
<%end%>
<%= link_to "Add Subscription" , fan_artists_path(@fan)%>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <p> <%=post.caption%> </p>
  <img src=<%= post.image_url %> >
  <p> Likes: <%= post.like%> </p>
<% end %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <p> <%= project.title %> </p>
  <p> Support: <%= project.support%>Ksh </p>
<% end %>